from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# Each class below becomes one table in MySQL when db.create_all() runs


class User(db.Model):
    # admin account, created directly in the database
    __tablename__ = "users"

    id            = db.Column(db.Integer, primary_key=True)
    email         = db.Column(db.String(200), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    role          = db.Column(db.String(50), default="admin")
    created_at    = db.Column(db.DateTime, server_default=db.func.now())


class PolicyEntry(db.Model):
    # syllabus snippet from an institution, managed via admin console
    __tablename__ = "syllabus_entries"

    id             = db.Column(db.Integer, primary_key=True)
    institution    = db.Column(db.String(300), nullable=False)
    department     = db.Column(db.String(200))
    policy_text    = db.Column(db.Text, nullable=False)
    tier_id        = db.Column(db.String(5),  nullable=False)
    compliance_id  = db.Column(db.String(5),  nullable=False)
    enforcement_id = db.Column(db.String(5),  nullable=False)
    status         = db.Column(db.String(20), default="pending")
    created_at     = db.Column(db.DateTime,   server_default=db.func.now())

    def to_dict(self):
        # so admin routes can return this as JSON easily
        return {
            "id":             self.id,
            "institution":    self.institution,
            "department":     self.department,
            "policy_text":    self.policy_text,
            "tier_id":        self.tier_id,
            "compliance_id":  self.compliance_id,
            "enforcement_id": self.enforcement_id,
            "status":         self.status,
            "created_at":     str(self.created_at),
        }


class BuilderQuestion(db.Model):
    #  question shown on the Build Syllabus page
    __tablename__ = "builder_questions"

    id       = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String(500), nullable=False)
    option_a = db.Column(db.String(200), nullable=False)
    value_a  = db.Column(db.String(100), nullable=False)
    option_b = db.Column(db.String(200), nullable=False)
    value_b  = db.Column(db.String(100), nullable=False)


class PolicyGenerated(db.Model):
    # AI policy generated by a faculty member via the builder
    __tablename__ = "policies"

    id            = db.Column(db.Integer, primary_key=True)
    course_name   = db.Column(db.String(200), nullable=False)
    policy_text   = db.Column(db.Text,        nullable=False)
    tier_id       = db.Column(db.String(10),  nullable=False)
    compliance_id = db.Column(db.String(10),  nullable=False)
    created_at    = db.Column(db.DateTime,    server_default=db.func.now())


class PolicyFragment(db.Model):
    # short policy snippet used in the training game
    __tablename__ = "policy_fragments"

    id        = db.Column(db.Integer, primary_key=True)
    text      = db.Column(db.Text, nullable=False)
    correct_t = db.Column(db.String(5), nullable=False)
    correct_c = db.Column(db.String(5), nullable=False)
    correct_e = db.Column(db.String(5), nullable=False)
